"""add subtotal tax discount to sale

Revision ID: 3fe3aea2eaaf
Revises: 83510e32ced1
Create Date: 2026-07-17 12:38:11.850097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe3aea2eaaf'
down_revision = '83510e32ced1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('tax')
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
