"""add barcode, expiry, supplier to products

Revision ID: 83510e32ced1
Revises: 342ea377b22b
Create Date: 2026-07-17 12:31:57.815649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83510e32ced1'
down_revision = '342ea377b22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_products_barcode', ['barcode'])
        batch_op.create_foreign_key('fk_products_supplier', 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_supplier', type_='foreignkey')
        batch_op.drop_constraint('uq_products_barcode', type_='unique')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
